[refactor] Content -> Post 엔티티 변경
2024-pre-onboarding-backend-F/social-media pull request #19
Opened 2024-08-25 07:33 UTC by pie2457

## Issue
- #18 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
ex) refactor/modify_post_entity -> dev

## 변경 사항
- Content -> Post로 클래스 네임 변경
- PK : Long -> String 으로 타입 변경
- ContentController -> PostController 클래스 네임 변경

2024-08-25 07:36 UTC, jw427 approved these changes
확인했습니다!

2024-08-25 07:36 UTC, jeongeungyeong approved these changes

2024-08-25 09:19 UTC, rhaehf requested changes

2024-08-25 09:19 UTC, rhaehf commented on src/main/java/wanted/media/content/domain/Post.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
id가 String 타입으로 바뀌면서 IDENTITY를 사용하면 에러가 나더라구요.
String 타입의 필드에 대한 자동 생성 값을 설정하려면 UUID로 변경하거나, 아니면 자동 생성 값을 사용하지 않아야 할 거 같습니다.
일단 저는 사용하지 않는게 더 낫다고 생각합니다.

2024-08-25 11:25 UTC, pie2457 commented on src/main/java/wanted/media/content/domain/Post.java
> +@Table(name = "post")
넵 변경 했습니다 !!

2024-08-25 11:26 UTC, pie2457 commented on src/main/java/wanted/media/content/domain/Post.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
헉 그러네요 일단 `@GeneratedValue` 자체를 삭제하겠습니다~

2024-08-25 11:29 UTC, rhaehf approved these changes

2024-08-25 11:31 UTC, rhaehf commented on src/main/java/wanted/media/content/domain/Post.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
네 감사합니다!

2024-08-25 11:32 UTC, rhaehf commented on src/main/java/wanted/media/content/domain/Post.java
> +@Table(name = "post")
수정해주신 커밋 확인했습니다!

2024-08-26 01:17 UTC, ssunnykku approved these changes
확인했습니다!

2024-08-26 03:00 UTC, merged